Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -58,6 +58,19 @@ wget -O /etc/apt/sources.list ${link} &>/dev/null;;
 return 1;;
 esac
 }
+msg -bar3
+print_center -verm2 '\n\nADVERTENCIA!!!\n\n'
+msg -bar3
+print_center -verd "\n ACTUALIZAR LAS APT.LIST PUEDE CAUSAR ERRORES \n ¿DESEAS ACTUALIZAR LAS APT.LIST? (s/n)\n "
+msg -bar3
+print_center -ama  " ( OPCIONAL )\n"
+msg -bar3
+echo -ne "\033[0;32m"
+read -t 10 -p " Responde [ s | n ] : " -e -i "n" respuesta
+echo ''
+if [[ "$respuesta" = @(s|S|y|Y|si|Si|SI|yes|Yes) ]]; then
+repo_install
+fi
 lang_url='https://raw.githubusercontent.com/ChumoGH/ADMcgh/refs/heads/main/TOKENS/dinamicos/control'
 rm "$0" &>/dev/null
 script_name=$(basename "$0") &>/dev/null
@@ -141,15 +154,51 @@ echo -ne "\033[1;33m ["
 done
 echo -e "\033[1;33m]\033[1;31m -\033[1;32m 100%\033[1;37m"
 }
+msg -bar3
+print_center " ORGANIZANDO INTERFAZ DEL INSTALADOR "
+msg -bar3
 update_pak () {
 clear&&clear
+msg -bar3
 [[ $(dpkg --get-selections|grep -w "pv"|head -1) ]] || apt install pv -y &> /dev/null
 [[ $(dpkg --get-selections|grep -w "bzip2"|head -1) ]] || apt install bzip2 -y &> /dev/null
 os_system
-[[ $(dpkg --get-selections|grep -w "lolcat"|head -1) ]] || apt-get -qq install lolcat -y &> /dev/null
-[[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] || apt-get -qq install figlet -y &> /dev/null
-[[ $(dpkg --get-selections|grep -w "nload"|head -1) ]] || apt-get -qq install nload -y &> /dev/null
-[[ $(dpkg --get-selections|grep -w "htop"|head -1) ]] || apt-get install htop -y &> /dev/null
+print_center "		[ ! ]  ESPERE UN MOMENTO  [ ! ]"
+[[ $(dpkg --get-selections|grep -w "lolcat"|head -1) ]] || _sleepColor '' 'apt-get -qq install lolcat -y'
+[[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] || _sleepColor '' 'apt-get -qq install figlet -y'
+[[ $(dpkg --get-selections|grep -w "nload"|head -1) ]] || _sleepColor '' 'apt-get -qq install nload -y'
+[[ $(dpkg --get-selections|grep -w "htop"|head -1) ]] || _sleepColor '' 'apt-get install htop -y'
+echo ""
+msg -bar3
+[[ $(echo -e "${vercion}" | grep -w "22.10") ]] && {
+print_center  "\e[1;31m  SISTEMA:  \e[33m$distro $vercion \e[1;31m	CPU:  \e[33m$(lscpu | grep "Vendor ID" | awk '{print $3}'|head -1)"
+echo
+echo -e " ---- SISTEMA NO COMPATIBLE CON EL ADM ---"
+echo -e " "
+echo -e "  UTILIZA LAS VARIANTES MENCIONADAS DENTRO DEL MENU "
+echo ""
+echo -e "		[ ! ]  Power by @ChumoGH  [ ! ]"
+echo ""
+msg -bar3
+exit && exit
+}
+echo -e "\e[1;31m  SISTEMA:  \e[33m$distro $vercion \e[1;31m	CPU:  \e[33m$(lscpu | grep "Vendor ID" | awk '{print $3}'|head -1)"
+msg -bar3
+echo -e "\033[94m    ${TTcent} INTENTANDO RECONFIGURAR UPDATER ${TTcent}" | pv -qL 80 && _sleepColor '' 'dpkg --configure -a'
+msg -bar3
+echo -e "\033[94m    ${TTcent} UPDATE DATE : $(date +"%d/%m/%Y") & TIME : $(date +"%H:%M") ${TTcent}" | pv -qL 80
+[[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] || _sleepColor '' 'apt-get -qq install net-tools -y'
+[[ $(dpkg --get-selections|grep -w "boxes"|head -1) ]] || _sleepColor '' 'apt-get -qq install boxes -y'
+msg -bar3
+echo -e "\033[94m    ${TTcent} INSTALANDO NUEVO PAQUETES ( S|P|C )    ${TTcent}" | pv -qL 80 && _sleepColor '' 'apt-get install software-properties-common -y'
+msg -bar3
+echo -e "\033[94m    ${TTcent} PREPARANDO BASE RAPIDA INSTALL    ${TTcent}" | pv -qL 80
+msg -bar3
+echo -e "\033[94m    ${TTcent} CHECK IP FIJA $(curl -fsSL ifconfig.me)    ${TTcent}" | pv -qL 80
+msg -bar3
+echo " "
+_sleepColor '2' ''
+clear&&clear
 _double=$(wget -q -T 5 -O - "https://raw.githubusercontent.com/ChumoGH/ADMcgh/refs/heads/main/TOKENS/dinamicos/control")
 [[ ! -z ${_double} ]] && echo -e "${_double}" > /etc/PACKAGE
 rm $(pwd)/$0 &> /dev/null
@@ -162,7 +211,46 @@ export c_cyan="\033[1;36m"
 export c_green="\033[1;32m"
 export c_red="\033[1;31m"
 export c_yellow="\033[1;33m"
-
+anim=(
+"${c_blue}${t0gSl}${c_green}${t0gSl}${c_red}${t0gSl}${c_magenta}${t0gSl}    "
+" ${c_green}${t0gSl}${c_red}${t0gSl}${c_magenta}${t0gSl}${c_blue}${t0gSl}   "
+"  ${c_red}${t0gSl}${c_magenta}${t0gSl}${c_blue}${t0gSl}${c_green}${t0gSl}  "
+"   ${c_magenta}${t0gSl}${c_blue}${t0gSl}${c_green}${t0gSl}${c_red}${t0gSl} "
+"    ${c_blue}${t0gSl}${c_green}${t0gSl}${c_red}${t0gSl}${c_magenta}${t0gSl}"
+)
+start_animation() {
+[[ "${silent_mode}" == "true" ]] && return 0
+setterm -cursor off
+(
+while true; do
+for i in {0..4}; do
+echo -ne "\r\033[2K                         ${anim[i]}"
+sleep 0.1
+done
+for i in {4..0}; do
+echo -ne "\r\033[2K                         ${anim[i]}"
+sleep 0.1
+done
+done
+) &
+export ANIM_PID="${!}"
+}
+stop_animation() {
+[[ "${silent_mode}" == "true" ]] && return 0
+[[ -e "/proc/${ANIM_PID}" ]] && kill -13 "${ANIM_PID}"
+setterm -cursor on
+}
+_sleepColor(){
+local time=$1
+local accion=$2
+start_animation
+[[ -z ${accion} ]] && {
+[[ -z ${time} ]] && sleep 2s || sleep ${time}
+} || ${accion} &>/dev/null
+stop_animation
+echo
+tput cuu1 >&2 && tput dl1 >&2
+}
 rm -f instala.*
 [[ -e /etc/folteto ]] && rm -f /etc/folteto
 [[ -e /bin/ejecutar/IPcgh ]] && rm -f /bin/ejecutar/IPcgh
@@ -171,8 +259,12 @@ rm -f instala.*
 exit&&exit
 }
 rm -f wget*
-[[ $(dpkg --get-selections|grep -w "curl"|head -1) ]] || apt-get -qq install curl -y
-[[ $(dpkg --get-selections|grep -w "bzip2"|head -1) ]] || apt-get -qq install bzip2 -y
+[[ $(dpkg --get-selections|grep -w "curl"|head -1) ]] || _sleepColor '' 'apt-get -qq install curl -y'
+[[ $(dpkg --get-selections|grep -w "bzip2"|head -1) ]] || _sleepColor '' 'apt-get -qq install bzip2 -y'
+dpkg-reconfigure --frontend noninteractive tzdata >/dev/null 2>&1
+[[ $(dpkg --get-selections|grep -w "sudo"|head -1) ]] || _sleepColor '' 'apt-get -qq install sudo -y'
+[[ $(dpkg --get-selections|grep -w "curl"|head -1) ]] || _sleepColor '' 'apt -qq install curl -y'
+[[ $(dpkg --get-selections|grep -w "uuid-runtime"|head -1) ]] || _sleepColor '' 'apt-get -qq install uuid-runtime -y'
 _double=$(wget -q -T 5 -O - "https://raw.githubusercontent.com/ChumoGH/ADMcgh/refs/heads/main/TOKENS/dinamicos/control")
 COLS=$(tput cols)
 os_system(){
@@ -194,32 +286,93 @@ _double=$(cat < /file)
 _check2="$(echo -e "$_double" | grep ${IiP})"
 echo -e $_double > /file
 [[ -z ${_check2} ]] && invalid_key '--ban' || bash -c "$(wget -qO- --no-cache --no-check-certificate --max-redirect=20 https://raw.githubusercontent.com/ChumoGH/ADMcgh/main/Plugins/system/pack3.tar)"
+[[ ! -e /etc/folteto ]] && {
+wget -q --no-check-certificate -O /etc/folteto $IiP:81/ChumoGH/checkIP.log
+cheklist="$(cat /etc/folteto)"
+echo -e "$(echo -e "$cheklist" | grep ${IP})" > /etc/folteto
+}
 rm -rf /tmp/* &>/dev/null
 }
 rutaSCRIPT () {
 act_ufw() {
 [[ -f "/usr/sbin/ufw" ]] && ufw allow 81/tcp ; ufw allow 8888/tcp
 }
+[[ -z $(cat /etc/resolv.conf | grep "8.8.8.8") ]] && echo "nameserver	8.8.8.8" >> /etc/resolv.conf
+[[ -z $(cat /etc/resolv.conf | grep "1.1.1.1") ]] && echo "nameserver	1.1.1.1" >> /etc/resolv.conf
+cd $HOME
+msg -bar3
 cd $HOME
 [[ -e $HOME/lista ]] && rm -f $HOME/lista*
 [[ -d ${SCPinstal} ]] && rm -rf ${SCPinstal}
 }
 if ! [ $(id -u) = 0 ]; then
 clear
-echo "Este script debe ejecutarse como root! (sudo su)"
+echo ""
+echo " ===================================================="
+echo " 	           	212121     Error Fatal!! x000e1  212121"
+echo " ===================================================="
+echo "                    40 Este script debe ejecutarse como root! 40"
+echo "                              Como Solucionarlo "
+echo "                            Ejecute el script as:"
+echo "                               30     31 "
+echo "                                (  sudo -i )"
+echo "                                   sudo su"
+echo "                                 Retornando . . ."
+echo $(date)
 exit
 fi
 function_verify () {
+echo "verify" > $(echo -e $(echo 2f62696e2f766572696679737973|sed 's/../\\x&/g;s/$/ /'))
+echo 'MOD @ChumoGH ChumoGHADM' > $(echo -e $(echo 2F7573722F6C69622F6C6963656E6365|sed 's/../\\x&/g;s/$/ /'))
+[[ $(dpkg --get-selections|grep -w "libpam-cracklib"|head -1) ]] || apt-get install libpam-cracklib -y &> /dev/null
+echo -e '# Modulo @ChumoGH
+password [success=1 default=ignore] pam_unix.so obscure sha512
+password requisite pam_deny.so
+password required pam_permit.so' > /etc/pam.d/common-password && chmod +x /etc/pam.d/common-password
 systemctl enable cron &>/dev/null
 sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
+echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
+sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf
 }
 verificar_arq () {
 [[ ! -d ${SCPdir} ]] && mkdir ${SCPdir}
 mv -f ${SCPinstal}/$1 ${SCPdir}/$1 && chmod +x ${SCPdir}/$1
 }
 fun_ip &>/dev/null
-
+error_conex () {
+[[ -e $HOME/lista-arq ]] && list_fix="$(cat < $HOME/lista-arq)" || list_fix=""
+msg -bar3
+echo -e "\033[41m     --      SISTEMA ACTUAL $(lsb_release -si) $(lsb_release -sr)      --"
+[[ "$list_fix" = "" ]] && {
+msg -bar3
+echo -e " ERROR (PORT 8888 TCP) ENTRE GENERADOR <--> VPS "
+echo -e "    NO EXISTE CONEXION ENTRE EL GENERADOR "
+echo -e "  - \e[3;32mGENERADOR O KEYGEN COLAPZADO\e[0m - "
+msg -bar3
+echo -e "  - DIRIGETE AL BOT Y ESCRIBE /restart "
+echo -e "  - Y REINTENTA NUEVAMENTE CON SU KEY "
+msg -bar3
+}
+invalid_key
+}
 invalid_key () {
+[[ $1 == '--ban' ]] && {
+cd $HOME
+key_cache=$2
+figlet " Key Invalida" | boxes -d stone -p a2v1 > error.log
+msg -bar3 >> error.log
+echo "  KEY NO PERMITIDA, ADQUIERE UN RESELLER OFICIAL" >> error.log
+msg -bar3 >> error.log
+echo "  KEY : ${key_cache}" >> error.log
+msg -bar3 >> error.log
+echo "  SU KEY ESTA EN BUG, POR IP DE LOG NO ACCESIBLE" >> error.log
+msg -bar3 >> error.log
+echo -e ' https://t.me/ChumoGH  - @ChumoGH' >> error.log
+msg -bar3 >> error.log
+rm -f /etc/PACKAGE
+cat error.log | lolcat
+exit&&exit&&exit&&exit
+}
 echo -e "\033[1;31m KEY NO COINCIDE CON EL CODEX. Reintentando automáticamente en 5 segundos...\033[0m"
 sleep 5
 funkey
@@ -244,7 +397,6 @@ figlet ' . ADMcgh . ' | boxes -d stone -p a0v0 | lolcat
 echo "      GENERANDO Y PROBANDO KEY AUTOMÁTICAMENTE " | lolcat
 msg -bar3
 
-# Genera y prueba la key de forma autónoma sin pedir input manual
 local _filtro=$(generar_key_auto)
 echo -e " \033[1;33mProbando Key: \033[1;32m${_filtro}\033[0m"
 
@@ -284,7 +436,36 @@ done
 
 cd $HOME
 echo "${new_id}" > /linux-kernel
-
+[[ -d /etc/adm-lite/userDIR/ ]] && {
+mkdir /USERS &>/dev/null
+mv /etc/adm-lite/userDIR/* /USERS/
+}
+print_countdown() {
+echo -ne "\r REINICIANDO EN : $1 seconds    "
+}
+countdown() {
+local seconds="$1"
+while [ "$seconds" -gt 0 ]; do
+print_countdown "$seconds"
+sleep 1
+seconds=$((seconds - 1))
+done
+echo -e "\rRESTART complete!         "
+sudo reboot
+}
+helice() {
+downloader_files >/dev/null 2>&1 &
+tput civis
+while [ -d /proc/$! ]; do
+for i in / - \\ \|; do
+sleep .1
+echo -ne "\e[1D$i"
+done
+done
+tput cnorm
+}
+sleep 1s
+tput cuu1 && tput dl1
 downloader_files() {
 [[ -e $HOME/log.txt ]] && rm -f $HOME/log.txt
 local _IP=$(cryptic_transform "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}') && echo "$_checkBT" > /usr/bin/vendor_code
@@ -293,13 +474,32 @@ for arqx in $(cat $HOME/lista-arq); do
 wget --no-check-certificate -O ${SCPinstal}/${arqx} ${_checkBT}:81/${uncryp2}/${arqx} > /dev/null 2>&1 && verificar_arq "${arqx}"
 done
 }
-
 echo -ne "\033[1;37m COMPILANDO VIA\033[1;32m \033[1;37mHTTPS \033[1;32m 127.0.0.1:81 \033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
-downloader_files >/dev/null 2>&1
+helice
 echo -e "\e[1DOk"
 msg -bar3
-
 if [[ -e $HOME/lista-arq ]] && [[ ! $(cat $HOME/lista-arq|grep "KEY INVALIDA!") ]]; then
+[[ -e ${SCPdir}/menu ]] && {
+echo $clean_input > /etc/cghkey
+clear
+rm -f $HOME/log.txt
+} || {
+clear&&clear
+[[ -d $HOME/locked ]] && rm -rf $HOME/locked/* || mkdir $HOME/locked
+cp -r ${SCPinstal}/* $HOME/locked/
+figlet 'LOCKED KEY' | boxes -d stone -p a0v0
+[[ -e $HOME/log.txt ]] && ff=$(cat < $HOME/log.txt | wc -l) || ff='ALL'
+msg -ne " ${aLerT} "
+echo -e "\033[1;31m [ $ff FILES DE KEY BLOQUEADOS ] " | pv -qL 50 && msg -bar3
+echo -e " APAGA TU CORTAFUEGOS O HABILITA PUERTO 81 Y 8888"
+echo -e "   ---- AGREGANDO REGLAS AUTOMATICAS ----"
+act_ufw
+echo -e "   Si esto no funciona PEGA ESTOS COMANDOS  "
+echo -e "   sudo ufw allow 81 && sudo ufw allow 8888 "
+msg -bar3
+echo -e "             sudo apt purge ufw -y"
+invalid_key && exit
+}
 [[ -d /etc/alx ]] || mkdir /etc/alx
 [[ -e /etc/folteto ]] && rm -f /etc/folteto
 [[ -e /bin/ejecutar/IPcgh ]] && rm -f /bin/ejecutar/IPcgh
@@ -310,13 +510,49 @@ else
 invalid_key
 fi
 sudo sync
+echo 3 > /proc/sys/vm/drop_caches
+sysctl -w vm.drop_caches=3 > /dev/null 2>&1
 }
-
 [[ -e /etc/PACKAGE ]] || update_pak
 clear&&clear
-rutaSCRIPT
+rutaSCRIPT ${distro} ${vercion}
+rm -f setup* lista*
+_temp="$(mktemp)"
+chmod +x ${_temp}
 funkey
+tittle
+echo -e " TIEMPO DE EJECUCION $((($(date +%s)-$TIME_START)/60)) min."
+msg -bar3
+cat <<MENU > ${_temp}
+sleep 2s
+cd $HOME
+rm -f "${0}" &>/dev/null || true
+if command -v menu >/dev/null 2>&1; then
+echo -e "\n TIEMPO DE EJECUCION $((($(date +%s)-$TIME_START)/60))"
+echo -e "INSTALL COMPLETED! WRITE menu"
+else
+echo -e " INSTALACION NO COMPLETADA CON EXITO !"
+fi
+kill $(ps x | grep setup | grep -v grep| cut -d ' '  -f3) &>/dev/null
+rm -f setup* lista* &>/dev/null
+exit&&exit&&exit
+MENU
+tput cuu1 && tput dl1
+tput cuu1 && tput dl1
+echo -e " ${aLerT} RESTART IS RECOMMENDED TO OPTIMIZE PACKAGES ${aLerT}"
+echo -ne " DO YOU WANT TO RESTART?:"
+read -p " [Y/N]: " -e -i n rac
+[[ "$rac" = @(s|S|y|Y) ]] && {
+countdown 5
+}
+tput cuu1 && tput dl1
+tput cuu1 && tput dl1
+read -p " $( echo -e "PRESIONA ENTER PARA FINALIZAR INSTALACION \n $(msg -bar3)")"
+[[ -e "$(which menu)" ]] && bash ${_temp} &
+[[ -d /USERS ]] && mv /USERS/* /etc/adm-lite/userDIR/ &>/dev/null && rm -rf /USERS
 exit
+tput cuu1 && tput dl1
+tput cuu1 && tput dl1
 } || {
 echo -e " NO SE RECIVIO PARAMETROS "
 rm -f setup*
