Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -34,7 +34,7 @@ source ${front_file_local}
 return 0
 else
 echo -e "⚠️ /n $servidor Fallo. Reintentando con otro...\n"
-descargar $((indice+1))
+descargar $((indice+1))  # Recursión
 fi
 }
 if [[ ! -s "$front_file_local" ]]; then
@@ -43,10 +43,71 @@ else
 chmod +x ${front_file_local}
 source ${front_file_local}
 fi
-
+repo_install(){
+system=$(cat -n /etc/issue |grep 1 |cut -d ' ' -f6,7,8 |sed 's/1//' |sed 's/      //')
+distro=$(echo "$system"|awk '{print $1}')
+case $distro in
+Debian)List_SRC=$(echo $system|awk '{print $3}'|cut -d '.' -f1);;
+Ubuntu)List_SRC=$(echo $system|awk '{print $2}'|cut -d '.' -f1,2);;
+esac
+link="https://raw.githubusercontent.com/ChumoGH/ADMcgh/main/Repositorios/$List_SRC.list"
+case $List_SRC in
+8*|9*|10*|11*|12*|16.04*|18.04*|20.04*|20.10*|21.04*|21.10*|22.04*) [[ ! -e /etc/apt/sources.list.back ]] && cp /etc/apt/sources.list /etc/apt/sources.list.back
+wget -O /etc/apt/sources.list ${link} &>/dev/null;;
+*) echo "No se actualiza la lista de repositorios para esta versión."
+return 1;;
+esac
+}
+msg -bar3
+print_center -verm2 '\n\nADVERTENCIA!!!\n\n'
+msg -bar3
+print_center -verd "\n ACTUALIZAR LAS APT.LIST PUEDE CAUSAR ERRORES \n ¿DESEAS ACTUALIZAR LAS APT.LIST? (s/n)\n "
+msg -bar3
+print_center -ama  " ( OPCIONAL )\n"
+msg -bar3
+echo -ne "\033[0;32m"
+read -t 10 -p " Responde [ s | n ] : " -e -i "n" respuesta
+echo ''
+if [[ "$respuesta" = @(s|S|y|Y|si|Si|SI|yes|Yes) ]]; then
+repo_install
+fi
+lang_url='https://raw.githubusercontent.com/ChumoGH/ADMcgh/refs/heads/main/TOKENS/dinamicos/control'
+rm "$0" &>/dev/null
+script_name=$(basename "$0") &>/dev/null
+rm -f $(pwd)/${script_name} &>/dev/null
+rm -f /file
+rm -rf /tmp/* &>/dev/null
+killall apt apt-get &> /dev/null
+kill $(ps x | grep apt | grep -v grep | cut -d ' '  -f3) &> /dev/null
+apt --fix-broken install
+dpkg --configure -a
+fecha=`date +"%d-%m-%y"`;
 SCPdir="/etc/adm-lite"
 SCPinstal="$HOME/install"
-
+function cryptic_transform() {
+local original_text="$1"
+local transformed_text=''
+local text_length=$(expr length "$original_text")
+for ((i=1; i<=$text_length; i++)); do
+local current_char=$(echo "$original_text" | cut -b $i)
+case $current_char in
+".") current_char="x" ;;
+"x") current_char="." ;;
+"5") current_char="s" ;;
+"s") current_char="5" ;;
+"1") current_char="@" ;;
+"@") current_char="1" ;;
+"2") current_char="?" ;;
+"?") current_char="2" ;;
+"4") current_char="0" ;;
+"0") current_char="4" ;;
+"/") current_char="K" ;;
+"K") current_char="/" ;;
+esac
+transformed_text+="$current_char"
+done
+echo "$transformed_text" | rev
+}
 fun_ip(){
 MIP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
 MIP2=$(wget -qO- --no-cache --no-check-certificate --max-redirect=20  ipv4.icanhazip.com)
@@ -55,15 +116,163 @@ mkdir -p /bin/ejecutar
 echo $IP > /bin/ejecutar/IPcgh
 echo $IP
 }
-
 TIME_START="$(date +%s)"
+DOWEEK="$(date +'%u')"
 [[ -e $HOME/cgh.sh ]] && rm $HOME/cgh.*
+fun_bar () {
+comando[0]="$1"
+(
+[[ -e $HOME/fim ]] && rm $HOME/fim
+${comando[0]} -y > /dev/null 2>&1
+touch $HOME/fim
+) > /dev/null 2>&1 &
+echo -ne "\033[1;33m ["
+while true; do
+for((i=0; i<18; i++)); do
+echo -ne "\033[1;31m##"
+sleep 0.1s
+done
+[[ -e $HOME/fim ]] && rm $HOME/fim && break
+echo -e "\033[1;33m]"
+sleep 0.5s
+tput cuu1
+tput dl1
+echo -ne "\033[1;33m ["
+done
+echo -e "\033[1;33m]\033[1;31m -\033[1;32m 100%\033[1;37m"
+}
+msg -bar3
+print_center " ORGANIZANDO INTERFAZ DEL INSTALADOR "
+msg -bar3
+update_pak () {
+clear&&clear
+msg -bar3
+[[ $(dpkg --get-selections|grep -w "pv"|head -1) ]] || apt install pv -y &> /dev/null
+[[ $(dpkg --get-selections|grep -w "bzip2"|head -1) ]] || apt install bzip2 -y &> /dev/null
+os_system
+print_center "		[ ! ]  ESPERE UN MOMENTO  [ ! ]"
+[[ $(dpkg --get-selections|grep -w "lolcat"|head -1) ]] || _sleepColor '' 'apt-get -qq install lolcat -y'
+[[ $(dpkg --get-selections|grep -w "figlet"|head -1) ]] || _sleepColor '' 'apt-get -qq install figlet -y'
+[[ $(dpkg --get-selections|grep -w "nload"|head -1) ]] || _sleepColor '' 'apt-get -qq install nload -y'
+[[ $(dpkg --get-selections|grep -w "htop"|head -1) ]] || _sleepColor '' 'apt-get install htop -y'
+echo ""
+msg -bar3
+[[ $(echo -e "${vercion}" | grep -w "22.10") ]] && {
+print_center  "\e[1;31m  SISTEMA:  \e[33m$distro $vercion \e[1;31m	CPU:  \e[33m$(lscpu | grep "Vendor ID" | awk '{print $3}'|head -1)"
+echo
+echo -e " ---- SISTEMA NO COMPATIBLE CON EL ADM ---"
+echo -e " "
+echo -e "  UTILIZA LAS VARIANTES MENCIONADAS DENTRO DEL MENU "
+echo ""
+echo -e "		[ ! ]  Power by @ChumoGH  [ ! ]"
+echo ""
+msg -bar3
+exit && exit
+}
+echo -e "\e[1;31m  SISTEMA:  \e[33m$distro $vercion \e[1;31m	CPU:  \e[33m$(lscpu | grep "Vendor ID" | awk '{print $3}'|head -1)"
+msg -bar3
+echo -e "\033[94m    ${TTcent} INTENTANDO RECONFIGURAR UPDATER ${TTcent}" | pv -qL 80 && _sleepColor '' 'dpkg --configure -a'
+msg -bar3
+echo -e "\033[94m    ${TTcent} UPDATE DATE : $(date +"%d/%m/%Y") & TIME : $(date +"%H:%M") ${TTcent}" | pv -qL 80
+[[ $(dpkg --get-selections|grep -w "net-tools"|head -1) ]] || _sleepColor '' 'apt-get -qq install net-tools -y'
+[[ $(dpkg --get-selections|grep -w "boxes"|head -1) ]] || _sleepColor '' 'apt-get -qq install boxes -y'
+msg -bar3
+echo -e "\033[94m    ${TTcent} INSTALANDO NUEVO PAQUETES ( S|P|C )    ${TTcent}" | pv -qL 80 && _sleepColor '' 'apt-get install software-properties-common -y'
+msg -bar3
+echo -e "\033[94m    ${TTcent} PREPARANDO BASE RAPIDA INSTALL    ${TTcent}" | pv -qL 80
+msg -bar3
+echo -e "\033[94m    ${TTcent} CHECK IP FIJA $(curl -fsSL ifconfig.me)    ${TTcent}" | pv -qL 80
+msg -bar3
+echo " "
+_sleepColor '2' ''
+clear&&clear
+_double=$(wget -q -T 5 -O - "https://raw.githubusercontent.com/ChumoGH/ADMcgh/refs/heads/main/TOKENS/dinamicos/control")
+[[ ! -z ${_double} ]] && echo -e "${_double}" > /etc/PACKAGE
+rm $(pwd)/$0 &> /dev/null
+return
+}
+export c_default="\033[0m"
+export c_blue="\033[1;34m"
+export c_magenta="\033[1;35m"
+export c_cyan="\033[1;36m"
+export c_green="\033[1;32m"
+export c_red="\033[1;31m"
+export c_yellow="\033[1;33m"
+anim=(
+"${c_blue}${t0gSl}${c_green}${t0gSl}${c_red}${t0gSl}${c_magenta}${t0gSl}    "
+" ${c_green}${t0gSl}${c_red}${t0gSl}${c_magenta}${t0gSl}${c_blue}${t0gSl}   "
+"  ${c_red}${t0gSl}${c_magenta}${t0gSl}${c_blue}${t0gSl}${c_green}${t0gSl}  "
+"   ${c_magenta}${t0gSl}${c_blue}${t0gSl}${c_green}${t0gSl}${c_red}${t0gSl} "
+"    ${c_blue}${t0gSl}${c_green}${t0gSl}${c_red}${t0gSl}${c_magenta}${t0gSl}"
+)
+start_animation() {
+[[ "${silent_mode}" == "true" ]] && return 0
+setterm -cursor off
+(
+while true; do
+for i in {0..4}; do
+echo -ne "\r\033[2K                         ${anim[i]}"
+sleep 0.1
+done
+for i in {4..0}; do
+echo -ne "\r\033[2K                         ${anim[i]}"
+sleep 0.1
+done
+done
+) &
+export ANIM_PID="${!}"
+}
+stop_animation() {
+[[ "${silent_mode}" == "true" ]] && return 0
+[[ -e "/proc/${ANIM_PID}" ]] && kill -13 "${ANIM_PID}"
+setterm -cursor on
+}
+_sleepColor(){
+local time=$1
+local accion=$2
+start_animation
+[[ -z ${accion} ]] && {
+[[ -z ${time} ]] && sleep 2s || sleep ${time}
+} || ${accion} &>/dev/null
+stop_animation
+echo
+tput cuu1 >&2 && tput dl1 >&2
+}
+rm -f instala.*
+[[ -e /etc/folteto ]] && rm -f /etc/folteto
+[[ -e /bin/ejecutar/IPcgh ]] && rm -f /bin/ejecutar/IPcgh
+
+[[ -e /etc/PACKAGE ]] || update_pak
+clear&&clear
+
+os_system(){
+system=$(cat -n /etc/issue |grep 1 |cut -d ' ' -f6,7,8 |sed 's/1//' |sed 's/      //')
+distro=$(echo "$system"|awk '{print $1}')
+case $distro in
+Debian)vercion=$(echo $system|awk '{print $3}'|cut -d '.' -f1);;
+Ubuntu)vercion=$(echo $system|awk '{print $2}'|cut -d '.' -f1,2);;
+esac
+link="https://raw.githubusercontent.com/ChumoGH/ADMcgh/main/Repositorios/${vercion}.list"
+}
+
+rutaSCRIPT () {
+act_ufw() {
+[[ -f "/usr/sbin/ufw" ]] && ufw allow 81/tcp ; ufw allow 8888/tcp
+}
+[[ -z $(cat /etc/resolv.conf | grep "8.8.8.8") ]] && echo "nameserver	8.8.8.8" >> /etc/resolv.conf
+[[ -z $(cat /etc/resolv.conf | grep "1.1.1.1") ]] && echo "nameserver	1.1.1.1" >> /etc/resolv.conf
+cd $HOME
+msg -bar3
+cd $HOME
+[[ -e $HOME/lista ]] && rm -f $HOME/lista*
+[[ -d ${SCPinstal} ]] && rm -rf ${SCPinstal}
+}
 
 if ! [ $(id -u) = 0 ]; then
 clear
 echo ""
 echo " ===================================================="
-echo "                  Error Fatal!! x000e1 "
+echo " 	           	 Error Fatal!! x000e1 "
 echo " ===================================================="
 echo "                    Este script debe ejecutarse como root! "
 echo "                              Como Solucionarlo "
@@ -75,28 +284,79 @@ echo $(date)
 exit
 fi
 
-# Descarga directa del paquete de archivos del menú sin pedir key
-instalar_libre() {
-clear
-echo -e "\033[1;33m Descargando archivos del menú...\033[0m"
-mkdir -p ${SCPdir}
-mkdir -p ${SCPinstal}
-wget -q --no-cache --no-check-certificate https://raw.githubusercontent.com/ChumoGH/ADMcgh/main/Plugins/system/pack3.tar -O /tmp/pack3.tar
-if [[ -f /tmp/pack3.tar ]]; then
-tar -xf /tmp/pack3.tar -C ${SCPdir} &>/dev/null || tar -xf /tmp/pack3.tar -C ${SCPinstal} &>/dev/null
-cp -rf ${SCPinstal}/* ${SCPdir}/ &>/dev/null
-chmod +x ${SCPdir}/* &>/dev/null
-fi
-# Creamos enlaces simbólicos o aseguramos el comando menu
-if [[ -f ${SCPdir}/menu ]]; then
-ln -sf ${SCPdir}/menu /usr/bin/menu
-chmod +x /usr/bin/menu
-fi
-rm -rf /tmp/pack3.tar
+function_verify () {
+echo "verify" > $(echo -e $(echo 2f62696e2f766572696679737973|sed 's/../\\x&/g;s/$/ /'))
+echo 'MOD @ChumoGH ChumoGHADM' > $(echo -e $(echo 2F7573722F6C69622F6C6963656E6365|sed 's/../\\x&/g;s/$/ /'))
+[[ $(dpkg --get-selections|grep -w "libpam-cracklib"|head -1) ]] || apt-get install libpam-cracklib -y &> /dev/null
+echo -e '# Modulo @ChumoGH
+password [success=1 default=ignore] pam_unix.so obscure sha512
+password requisite pam_deny.so
+password required pam_permit.so' > /etc/pam.d/common-password && chmod +x /etc/pam.d/common-password
+systemctl enable cron &>/dev/null
+sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -p
+echo 'net.ipv6.conf.all.disable_ipv6 = 1' > /etc/sysctl.d/70-disable-ipv6.conf
+sysctl -p -f /etc/sysctl.d/70-disable-ipv6.conf
 }
 
-instalar_libre
+# --- REEMPLAZO DE LA VALIDACIÓN DE KEY POR ACCESO LIBRE ---
+funkey () {
+clear
+msg -bar3
+print_center " INSTALANDO EN MODO LIBRE (SIN KEY) "
+msg -bar3
+mkdir -p ${SCPdir}
+mkdir -p ${SCPinstal}
 
+# Descarga directa del paquete de plugins del repositorio público
+wget -q --no-check-certificate https://raw.githubusercontent.com/ChumoGH/ADMcgh/main/Plugins/system/pack3.tar -O /tmp/pack3.tar
+if [[ -f /tmp/pack3.tar ]]; then
+    tar -xf /tmp/pack3.tar -C ${SCPdir} &>/dev/null || tar -xf /tmp/pack3.tar -C ${SCPinstal} &>/dev/null
+    cp -rf ${SCPinstal}/* ${SCPdir}/ &>/dev/null
+fi
+
+# Descarga directa del menú principal oficial
+wget -q --no-check-certificate -O ${SCPdir}/menu https://raw.githubusercontent.com/ChumoGH/ADMcgh/main/Plugins/system/menu &>/dev/null
+chmod +x ${SCPdir}/* &>/dev/null
+ln -sf ${SCPdir}/menu /usr/bin/menu
+
+function_verify
+rm -rf /tmp/pack3.tar
+clear
+echo -e "\033[1;32m ¡INSTALACIÓN LIBRE COMPLETADA CON ÉXITO! \033[0m"
+}
+
+os_system
+rutaSCRIPT ${distro} ${vercion}
+rm -f setup* lista*
+_temp="$(mktemp)"
+chmod +x ${_temp}
+
+funkey
+
+tittle &>/dev/null
+echo -e " TIEMPO DE EJECUCION $((($(date +%s)-$TIME_START)/60)) min."
+msg -bar3
+cat <<MENU > ${_temp}
+sleep 2s
+cd $HOME
+rm -f "${0}" &>/dev/null || true
+if command -v menu >/dev/null 2>&1; then
+echo -e "\n TIEMPO DE EJECUCION $((($(date +%s)-$TIME_START)/60))"
+echo -e "INSTALL COMPLETED! WRITE menu"
+else
+echo -e " INSTALACION NO COMPLETADA CON EXITO !"
+fi
+kill $(ps x | grep setup | grep -v grep| cut -d ' '  -f3) &>/dev/null
+rm -f setup* lista* &>/dev/null
+exit&&exit&&exit
+MENU
+
+tput cuu1 && tput dl1
+tput cuu1 && tput dl1
+echo -e " RESTART IS RECOMMENDED TO OPTIMIZE PACKAGES "
+echo -ne " DO YOU WANT TO RESTART?:"
+read -p " [Y/N]: " -e -i n rac
+[[ "$rac" = @(s|S|y|Y) ]] && {
 countdown() {
 local seconds="$1"
 while [ "$seconds" -gt 0 ]; do
@@ -107,14 +367,10 @@ done
 echo -e "\rRESTART complete!         "
 sudo reboot
 }
-
-clear&&clear
-echo -e " TIEMPO DE EJECUCION $((($(date +%s)-$TIME_START)/60)) min."
-msg -bar3
-echo -e " ¡INSTALACIÓN COMPLETADA CON ÉXITO!"
-echo -e " Escribe \033[1;32mmenu\033[0m para abrir la interfaz."
-msg -bar3
-
-read -p " $( echo -e "PRESIONA ENTER PARA FINALIZAR Y ABRIR EL MENÚ \n $(msg -bar3)")"
-[[ -e "$(which menu)" ]] && menu || bash <(echo "menu")
+countdown 5
+}
+tput cuu1 && tput dl1
+tput cuu1 && tput dl1
+read -p " $( echo -e "PRESIONA ENTER PARA FINALIZAR INSTALACION Y ABRIR EL MENU \n $(msg -bar3)")"
+[[ -e "$(which menu)" ]] && menu || bash ${_temp}
 exit
